import type { Batch, Detector, Device, Evidence, Mission } from "./engine.js";
import { batch, cheap, device, direct, PRECISE, report, sample, SCREEN, test } from "./jobs.js";

const unit = (id: string, title: string, requester: string, prior: number, replaceCost: number, faultLoss: number,
  detectors: readonly Detector[] = [SCREEN, PRECISE], evidence: readonly Evidence[] = []): Device => ({
  ...device, id, title, requester, prior, replaceCost, faultLoss, detectors, evidence,
  request: "请比较已有资料和检测费用，安排追加检测，以及每种结果下的处理。",
});
const lot = (id: string, title: string, count: number, rates: readonly number[], weights: readonly number[],
  replaceCost: number, faultLoss: number, sampleCost = 1): Batch => ({
  ...batch, id, title, count, rates, weights, replaceCost, faultLoss, sampleCost,
  request: `共 ${count} 件待用设备。先决定检查几件样品，再填写什么情况下更换整批。`,
});

const JOBS = {
  rare: unit("rare-lamp", "备用灯的标红报告", "许老师", 0.001, 18, 80, [], [report]),
  worn: unit("worn-fan", "旧风机的标红报告", "周师傅", 0.35, 8, 40, [], [report]),
  green: unit("green-pump", "未标红的旧水泵", "周师傅", 0.7, 18, 300, [SCREEN, PRECISE], [{ ...report, red: false }]),
  quiet: unit("quiet-radio", "偶尔有杂音的收音机", "陆阿姨", 0.005, 10, 80),
  wornCheap: unit("worn-switch", "常出故障的旧开关", "周师傅", 0.9, 5, 40),
  copies: unit("copied-projector", "一份报告的两张抄件", "许老师", 0.02, 16, 70, [PRECISE], [report, { ...report, title: "办公室转录件" }]),
  independent: unit("independent-projector", "两次测量都标红的灯", "许老师", 0.02, 16, 70, [PRECISE], [report, { ...report, source: "测量 A-18", title: "第二次初筛" }]),
  pump: unit("pump", "工坊的供水泵", "周师傅", 0.12, 20, 100),
  alarm: unit("alarm", "社区的报警器", "陆阿姨", 0.03, 6, 220, [cheap, PRECISE]),
  fan: unit("fan", "学校的通风机", "许老师", 0.4, 12, 60, [cheap, PRECISE]),
  latch: unit("latch", "冷库的门控器", "周师傅", 0.18, 8, 90),
  router: unit("router", "社区的广播控制器", "陆阿姨", 0.08, 22, 100, [cheap, PRECISE]),
  loan: unit("loan-lamp", "借用台架检查的灯", "许老师", 0.02, 12, 60, [{ ...PRECISE, cost: 10 }], [report]),
  urgent: unit("urgent-valve", "工坊的紧急阀门", "周师傅", 0.22, 16, 170, [SCREEN, { ...PRECISE, cost: 2, work: 3 }]),
  switches: lot("switches", "工坊的开关", 10, [0.02, 0.1, 0.3], [0.5, 0.3, 0.2], 6, 60),
  plugs: lot("plugs", "学校的插头", 8, [0.05, 0.2, 0.5], [0.55, 0.3, 0.15], 12, 55),
  seals: lot("seals", "工坊的密封圈", 12, [0.04, 0.18, 0.5], [0.45, 0.35, 0.2], 7, 45, 2),
  buttons: lot("buttons", "社区的控制按钮", 16, [0.01, 0.06, 0.22], [0.4, 0.35, 0.25], 4, 65),
  sensors: lot("sensors", "冷库的温度探头", 6, [0.03, 0.12, 0.4], [0.6, 0.25, 0.15], 12, 80, 2),
  spares: lot("spares", "学校的备用插座", 10, [0.005, 0.02, 0.08], [0.75, 0.2, 0.05], 12, 35),
  relays: lot("relays", "工坊的继电器", 9, [0.02, 0.16, 0.45], [0.3, 0.4, 0.3], 20, 70, 2),
  contacts: lot("contacts", "社区的接触器", 8, [0.1, 0.35, 0.7], [0.55, 0.3, 0.15], 24, 55),
  lamps: lot("lamp-batch", "学校的一批走廊灯", 14, [0.02, 0.1, 0.28], [0.6, 0.25, 0.15], 5, 75),
};

export const CHALLENGES: readonly Mission[] = [
  {
    id: 9, title: "同样标红的两张单", concept: "原有概率 · 条件概率",
    opening: "许老师送来备用灯，周师傅送来旧风机，两张报告都标红。罗师傅把使用记录放到报告旁：“先看看各自过去多常出故障，再决定换不换。”今天不用追加检测，两份单都由你处理。",
    cases: [JOBS.rare, JOBS.worn], budget: 0, work: 0, goal: 10, efficient: 9.5, seed: 909,
    hints: ["同样亮红灯，报告之前的故障概率可能相差很远。分别比较保留的平均故障损失和更换费。", "备用灯原有故障概率 0.1%，旧风机为 35%；两张报告的检出率和误报率相同。", "备用灯保留、旧风机直接更换，平均损失合计约 9.42 点。"],
    reference: [direct("keep"), direct("replace")], recap: "标红后的判断还取决于设备原本多常出故障，两张红灯报告可以对应不同处理。",
  },
  {
    id: 10, title: "没亮红灯的水泵", concept: "漏检 · 故障后果",
    opening: "周师傅送来的水泵初筛没有标红，但这型号过去常出故障。陆阿姨的收音机也在桌上。罗师傅指着两份单：“先把故障可能造成的损失算进去，检测台今天只够再用一轮。”",
    cases: [JOBS.green, JOBS.quiet], budget: 3, work: 2, goal: 11, efficient: 10, seed: 1010,
    hints: ["未标红后的故障概率仍可能让保留设备的平均损失高于更换费。两份单分别核算。", "水泵未标红后的故障概率约 19.72%，一次故障损失 300 点。收音机原有故障概率为 0.5%。", "水泵用台架复检，标红更换、未标红保留；收音机直接保留。总平均损失约 9.87 点。"],
    reference: [test("precise"), direct("keep")], recap: "没亮红灯仍可能漏掉故障，是否继续检测要结合故障概率、费用和故障后果。",
  },
  {
    id: 11, title: "页脚上的两个编号", concept: "独立测量 · 报告去重",
    opening: "学校两盏灯各有两张标红报告。第一盏的页脚都写着 A-17，第二盏分别写着 A-17 和 A-18。罗师傅请你核完资料再用台架：“今天的复检预算只够一盏。”",
    cases: [JOBS.copies, JOBS.independent], budget: 3, work: 2, goal: 25, efficient: 24.2, seed: 1111,
    hints: ["报告张数相同，实际测量次数可能不同。先核对来源编号，再比较是否值得复检。", "第一盏只测过一次，故障概率约 26.87%；第二盏确实测了两次，故障概率约 86.86%。", "第一盏台架复检、标红换未标红留；第二盏直接更换。总平均损失约 24.14 点。"],
    reference: [test("precise"), direct("replace")], recap: "抄件只算一次测量，两次独立标红会让故障判断更高，也会改变复检是否划算。",
  },
  {
    id: 12, title: "几件坏的才换", concept: "样本结果 · 更换门槛",
    opening: "学校的插头和社区的接触器一起送到了，整批更换的费用不同。罗师傅把生产记录递给你：“每份单都能查四件样品。查出坏件后要怎么处理，先在方案里写清楚。”",
    cases: [JOBS.plugs, JOBS.contacts], budget: 8, work: 8, goal: 177, efficient: 175, seed: 1212,
    hints: ["取样数量与更换门槛要一起比较。查出一件坏样品时，整批更换未必比保留的平均损失少。", "插头每件更换费 12 点，接触器为 24 点。两批每件故障损失都是 55 点，生产状态的概率也要分别看。", "两批都检查 4 件。插头至少 2 件坏才全换；接触器至少 3 件坏才全换。总平均损失约 174.72 点。"],
    reference: [sample(4, 2), sample(4, 3)], recap: "相同的坏样品数量，换货成本和生产记录不同，适合的整批更换门槛也会不同。",
  },
  {
    id: 13, title: "台架只够一份", concept: "调查收益 · 预算分配",
    opening: "供水泵、报警器和通风机都在等检修。罗师傅给你 4 点调查费、3 格工时：“先把每份单查与不查的损失列出来，再分配工具。”",
    cases: [JOBS.pump, JOBS.alarm, JOBS.fan], budget: 4, work: 3, goal: 21, efficient: 20.1, seed: 1313,
    hints: ["先给每份单安排不检测的处理，比较检测后能减少多少平均损失。不要只挑单份收益最大的工具。", "台架占 2 格工时，快速筛查占 1 格。三份单合用 4 点预算，报警器也可以不检测直接处理。", "供水泵快速筛查、通风机台架复检，都是标红换未标红留；报警器直接更换。总平均损失 20.072 点。"],
    reference: [test("screen"), direct("replace"), test("precise")], recap: "调查费要放进整套方案比较，单份检修最省损失的工具未必都能安排上。",
  },
  {
    id: 14, title: "便宜台架占工时", concept: "费用与工时 · 双重约束",
    opening: "紧急阀门的台架复检只收 2 点，却要占 3 格工时。供水泵和门控器也没修好。罗师傅把工时簿放在费用单旁：“两本账都要够，才能一起执行。”",
    cases: [JOBS.urgent, JOBS.pump, JOBS.latch], budget: 5, work: 4, goal: 19, efficient: 18.1, seed: 1414,
    hints: ["工具花钱少，占用的检查工作量也可能多。把每份单的费用和工时分别加起来。", "阀门台架要 3 格，另两份各用快速筛查又要 2 格，会超过 4 格工时。", "三份都用快速筛查，标红换未标红留。花 3 点、占 3 格，平均损失 18.016 点。预算可以留着不用。"],
    reference: [test("screen"), test("screen"), test("screen")], recap: "便宜的工具也可能占用更多工时，费用与工时要分别满足，剩余预算不必花完。",
  },
  {
    id: 15, title: "三批货共用样品台", concept: "取样数量 · 共享资源",
    opening: "周师傅催着装开关和密封圈，学校也等着这一批插头。样品台只够 6 格工时，调查费共 8 点。罗师傅留下三份生产记录，让你安排每批检查多少。",
    cases: [JOBS.switches, JOBS.plugs, JOBS.seals], budget: 8, work: 6, goal: 190, efficient: 189, seed: 1515,
    hints: ["多查一件带来的损失变化，不一定每批相同。先比较每份单的不同样本数，再凑整套预算和工时。", "密封圈每件样品花 2 点，开关和插头各花 1 点。三批全查四件会超预算，也会超工时。", "开关查 3 件、插头查 1 件、密封圈查 2 件，三批都是至少 1 件坏就全换。花 8 点、占 6 格，总平均损失约 188.89 点。"],
    reference: [sample(3, 1), sample(1, 1), sample(2, 1)], recap: "样品要按每批的损失变化分配，平均分配数量可能错过更值得调查的任务。",
  },
  {
    id: 16, title: "留着不用的预算", concept: "调查成本 · 直接处理",
    opening: "借来的台架费用又涨了，学校和工坊送来三台设备，还有冷库的一批探头。罗师傅留下 7 点预算：“先决定哪些值得查，剩下的钱留在账上也行。”",
    cases: [JOBS.loan, JOBS.quiet, JOBS.wornCheap, JOBS.sensors], budget: 7, work: 4, goal: 66, efficient: 64.6, seed: 1616,
    hints: ["直接更换与直接保留都不占调查资源。每份单先算不检测的平均损失，再考虑是否追加。", "借来的台架收 10 点，无法放进本章预算；旧开关本来就很容易坏，更换只花 5 点。", "投影灯和旧开关直接更换，收音机保留；探头查 2 件，至少 1 件坏就全换。调查花 4 点、占 2 格，平均损失约 64.57 点。"],
    reference: [direct("replace"), direct("keep"), direct("replace"), sample(2, 1)], recap: "调查只在减少的平均损失超过调查成本时值得做，直接处理也能留下合用的方案。",
  },
  {
    id: 17, title: "报告和新货一起到", concept: "证据来源 · 资源取舍",
    opening: "学校又送来两份报告，工坊的水泵与社区的按钮也要一起处理。罗师傅请你接下这四份单：“已有测量、新检测、批次取样都在资料里，先分清来源，再安排。”",
    cases: [JOBS.copies, JOBS.independent, JOBS.green, JOBS.buttons], budget: 7, work: 5, goal: 99, efficient: 97.7, seed: 1717,
    hints: ["查样品和复检单台设备共用预算。先看已有报告已经改变了哪些判断，再比较额外调查的收益。", "两次独立标红的灯和报告抄件不同；水泵虽然未标红，留下故障的损失仍高。", "报告抄件那盏灯与水泵都用台架，标红换未标红留；两次标红的灯直接换，按钮不取样、总是更换。总平均损失约 97.61 点。"],
    reference: [test("precise"), direct("replace"), test("precise"), sample(0, 0)], recap: "已有证据会改变追加调查的价值，取样与复检要放在同一份预算里比较。",
  },
  {
    id: 18, title: "样品少给谁一件", concept: "取样收益 · 整套策略",
    opening: "四批货占满了检修桌。周师傅把每批更换费都写好了，冷库还添了一份探头记录。今天只能做 7 格检查，罗师傅让你选好样本数后一起交单。",
    cases: [JOBS.switches, JOBS.seals, JOBS.buttons, JOBS.sensors], budget: 10, work: 7, goal: 236, efficient: 234.3, seed: 1818,
    hints: ["先比较不取样的处理，再观察每批多查一件能改变哪些结果分支。样本数和更换门槛都由你决定。", "密封圈和探头每件样品花 2 点。只看哪批待用件数最多，会忽略调查费与样品带来的实际收益。", "开关查 4 件、密封圈查 2 件、探头查 1 件，均至少 1 件坏全换；按钮不取样、总是更换。调查 10 点、7 格，平均损失约 234.26 点。"],
    reference: [sample(4, 1), sample(2, 1), sample(0, 0), sample(1, 1)], recap: "取样价值要看整批后果和各结果分支，检查数量最多的批次未必最值得继续查。",
  },
  {
    id: 19, title: "街区集中送修", concept: "工具与取样 · 组合分配",
    opening: "学校、社区和工坊把六份单集中送来。罗师傅在交班簿写下 10 点预算、8 格工时，随后去送上一班修好的设备。你负责把单台检测与两批取样一起安排。",
    cases: [JOBS.pump, JOBS.alarm, JOBS.fan, JOBS.latch, JOBS.plugs, JOBS.contacts], budget: 10, work: 8, goal: 202, efficient: 200.4, seed: 1919,
    hints: ["先给全部检修单一个直接处理方案，再比较能用调查减少多少损失。单台和批次用同一份资源账。", "台架占 2 格；每件样品占 1 格。接触器更换费较高，坏样品的更换门槛也要重新检查。", "供水泵、门控器快速筛查，报警器便携检测，通风机台架复检，均标红换未标红留；插头查 1 件、至少 1 件坏全换，接触器查 2 件、至少 2 件坏全换。总平均损失约 200.29 点。"],
    reference: [test("screen"), test("cheap"), test("precise"), test("screen"), sample(1, 1), sample(2, 2)], recap: "单台检测和批次取样共用资源，工具与处置门槛要一起放进整套方案核算。",
  },
  {
    id: 20, title: "晚班的六张单", concept: "追加调查 · 工时分配",
    opening: "晚班员送来报告抄件、广播控制器、阀门和三批货。预算还有 9 点，工时只剩 6 格。罗师傅把已有报告放在单台设备旁，全部生产记录都留在检修桌上，你来完成这班。",
    cases: [JOBS.copies, JOBS.router, JOBS.urgent, JOBS.switches, JOBS.sensors, JOBS.spares], budget: 9, work: 6, goal: 129, efficient: 127.7, seed: 2020,
    hints: ["先看哪些单不调查也有低损失方案，把工时留给改变处置最有价值的调查。", "备用插座原有平均故障率较低；阀门台架占 3 格。六份单的平均损失要一起达到目标。", "报告抄件那盏灯台架复检，阀门快速筛查，均标红换未标红留；广播控制器直接保留；开关查 2 件、探头查 1 件，均至少 1 件坏全换；备用插座不取样、总是保留。平均损失约 127.60 点。"],
    reference: [test("precise"), direct("keep"), test("screen"), sample(2, 1), sample(1, 1), sample(0, 1)], recap: "调查资源有限时，已有低损失处理的任务可以少查，把工时留给其他检修单。",
  },
  {
    id: 21, title: "台架与样品台都排队", concept: "综合值班 · 双重资源",
    opening: "七份检修单排进工坊，台架与样品台用同一本工时簿。周师傅把更换报价和生产记录送齐，罗师傅让你独立交班：调查不超过 12 点、8 格，平均损失不超过 348 点。",
    cases: [JOBS.green, JOBS.fan, JOBS.quiet, JOBS.buttons, JOBS.seals, JOBS.relays, JOBS.plugs], budget: 12, work: 8, goal: 348, efficient: 346.3, seed: 2121,
    hints: ["预算和工时分别合计。某份单上更准确的检测，可能挤掉另一份单的有效取样。", "水泵与通风机都能用台架，但全部上台架后还要核对四批货的样品。直接更换也要计入平均损失。", "水泵快速筛查、通风机台架复检，标红换未标红留；收音机保留、按钮不取样总是换；密封圈查 2 件、继电器查 1 件、插头查 2 件，均至少 1 件坏全换。总平均损失约 346.23 点。"],
    reference: [test("screen"), test("precise"), direct("keep"), sample(0, 0), sample(2, 1), sample(1, 1), sample(2, 1)], recap: "给一份单换更准确的工具之前，要把挤掉的其他调查也算进总损失。",
  },
  {
    id: 22, title: "八份单的交班账", concept: "调查分配 · 收益与资源",
    opening: "社区与工坊的八份单同时到了。罗师傅把 13 点调查费留给你，工时簿只有 9 格。每份单都要写好完整处理条件，再由你执行整套方案。",
    cases: [JOBS.pump, JOBS.alarm, JOBS.latch, JOBS.router, JOBS.switches, JOBS.sensors, JOBS.relays, JOBS.spares], budget: 13, work: 9, goal: 247, efficient: 244.6, seed: 2222,
    hints: ["比较每份单不查与查后的总损失，再核对两项资源。花完预算也不能补回工时不足。", "广播控制器的台架复检占 2 格。它节省的损失，要和把这些工时交给开关、探头或继电器的方案比较。", "供水泵和门控器快速筛查、报警器便携检测，均标红换未标红留；广播控制器直接保留；开关查 4 件、探头与继电器各查 1 件，均至少 1 件坏全换；备用插座保留。总平均损失约 244.56 点。"],
    reference: [test("screen"), test("cheap"), test("screen"), direct("keep"), sample(4, 1), sample(1, 1), sample(1, 1), sample(0, 1)], recap: "每格工时能减少多少损失也要比较，预算有余时仍可能需要放弃一份有效调查。",
  },
  {
    id: 23, title: "送修车停在门口", concept: "综合检修 · 十份方案",
    opening: "送修车留下十份单，司机等着把修好的设备送回街区。罗师傅把资料按对象放齐，给你 16 点调查费和 11 格工时。你要自行检查报告来源、选工具、定取样与更换条件，再交整班账。",
    cases: [JOBS.copies, JOBS.independent, JOBS.urgent, JOBS.fan, JOBS.quiet, JOBS.plugs, JOBS.seals, JOBS.buttons, JOBS.lamps, JOBS.spares], budget: 16, work: 11, goal: 315, efficient: 313, seed: 2323,
    hints: ["先按每份单直接处理的损失排出基准，再比较不同调查组合。把已有报告和新的样品分清，避免用同一规则处理全部任务。", "两盏灯的实际测量次数不同；阀门台架占用较多工时。走廊灯有 14 件，更换成本与样品结果的影响要一起核算。", "报告抄件那盏灯台架复检、阀门快速筛查，均标红换未标红留；两次标红的灯和通风机直接换，收音机保留；插头查 1 件、密封圈查 3 件、走廊灯查 4 件，均至少 1 件坏全换；按钮总是换、备用插座总是留。总平均损失约 312.91 点。"],
    reference: [test("precise"), direct("replace"), test("screen"), direct("replace"), direct("keep"), sample(1, 1), sample(3, 1), sample(0, 0), sample(4, 1), sample(0, 1)], recap: "报告、检测和样品最终都要接到处理条件，再把整班的资源与平均损失一起核对。",
  },
  {
    id: 24, title: "检修站交班日", concept: "综合决策 · 独立交班",
    opening: "街区检修站今天由你值班。学校、工坊和社区送来十二份单，罗师傅把 18 点调查费与 12 格工时写在交班簿上，随后出门送货。所有报告、工具效果、报价与生产记录都已备齐。请完成整套方案，平均损失不超过 401.5 点。",
    cases: [JOBS.copies, JOBS.independent, JOBS.green, JOBS.urgent, JOBS.pump, JOBS.alarm, JOBS.loan, JOBS.quiet, JOBS.switches, JOBS.contacts, JOBS.sensors, JOBS.relays], budget: 18, work: 12, goal: 401.5, efficient: 399.5, seed: 2424,
    hints: ["给十二份单分别建立直接处理方案，再尝试把调查分给不同任务。每次修改都同时检查预算、工时和总平均损失，不能只看单份改善最大。", "报告抄件与独立测量要分开。阀门的便宜台架占 3 格，借来的灯台架收 10 点；接触器的更换门槛不能沿用其他批次。", "抄件那盏灯台架复检，水泵、阀门、供水泵快速筛查，均标红换未标红留；两次标红的灯、报警器、借台架的灯直接换，收音机留；开关查 3 件至少 1 件坏全换，接触器查 2 件至少 2 件坏全换，探头和继电器各查 1 件至少 1 件坏全换。调查 15 点、12 格，总平均损失约 399.43 点。"],
    reference: [test("precise"), direct("replace"), test("screen"), test("screen"), test("screen"), direct("replace"), direct("replace"), direct("keep"), sample(3, 1), sample(2, 2), sample(1, 1), sample(1, 1)], recap: "先核查证据，再按结果制定处理条件，把调查价值和整班资源一起比较，才能完成交班。",
  },
];
