import type { Mission, Place } from "./engine.js";
import { edge, place, route } from "./roads.js";

const receiver = (id: string, name: string, y: number, need: number): Place =>
  place(id, name, 91, y, need, `${name}清点完补给，${need} 箱已经按这班的需求备齐，可以开始分发。`);
const fork = (need: number): Place[] => [
  place("S", "总仓", 9, 50), place("A", "北站", 34, 20), place("B", "南站", 34, 80),
  place("C", "桥头站", 63, 50), receiver("T", "河岸站", 50, need),
];
const crossing = (need: number): Place[] => [
  place("S", "总仓", 8, 50), place("A", "北站", 30, 20), place("B", "南站", 30, 80),
  place("C", "上桥头", 59, 20), place("D", "下桥头", 59, 80), receiver("T", "河岸站", 50, need),
];
const district = (...needs: number[]): Place[] => {
  const rows = needs.length === 4 ? [10, 36, 63, 89] : needs.length === 3 ? [15, 50, 85] : needs.length === 2 ? [25, 75] : [50];
  const junctionRows = needs.length === 4 ? [10, 36, 63, 89] : [15, 50, 85];
  return [place("S", "总仓", 8, 50), place("A", "北站", 27, 15), place("B", "南站", 27, 50), place("C", "坡口站", 27, 85),
    ...["上桥头", "中桥头", "下桥头", "街口站"].slice(0, junctionRows.length).map((name, i) => place("DEFG"[i], name, 58, junctionRows[i])),
    ...needs.map((need, i) => receiver("TUVW"[i], ["河岸站", "山脚站", "学校", "冷库"][i], rows[i], need))];
};

export const CHALLENGES: readonly Mission[] = [
  {
    id: 9, title: "便宜通道留给谁", concept: "共享容量 · 两站分配",
    opening: "山脚站要 3 箱，河岸站要 4 箱。北站的通道便宜，但总仓到北站只能安排 4 箱。许衡把两份需求放在一起：“先把两边的路线都看完，整班运费控制在 12 点以内。”",
    places: [place("S", "总仓", 9, 50), place("A", "北站", 45, 22), place("B", "南站", 45, 78), receiver("T", "河岸站", 22, 4), receiver("U", "山脚站", 78, 3)],
    edges: [edge("S", "A", 4, 0), edge("S", "B", 4), edge("A", "T", 4), edge("A", "U", 3, 0, -65), edge("B", "T", 1, 2), edge("B", "U", 4, 2)],
    source: "S", supply: 7, budget: 20, costGoal: 12, efficient: 12,
    reference: [route("SAT", 3), route("SAU", 1), route("SBT", 1), route("SBU", 2)],
    hints: ["便宜路线的箱数也受容量限制。先看哪一站离开北站后仍有足够的替代路线。", "南站到河岸站只能运 1 箱，河岸站至少有 3 箱要经过北站。", "北站送河岸站 3 箱、山脚站 1 箱；南站送河岸站 1 箱、山脚站 2 箱。两站收齐，合计 12 点。"],
    recap: "先占用便宜通道，可能挤掉另一站必需的容量，两站的路线要一起安排。",
  },
  {
    id: 10, title: "箭头朝着北站", concept: "方向 · 路线费用",
    opening: "南站到北站开了一条免费单向通道。周姨要 6 箱，许衡把收费表贴在地图旁：“路看着绕，费用未必高。顺着箭头排好路线，这班运费最多 26 点。”",
    places: fork(6),
    edges: [edge("S", "A", 4), edge("S", "B", 4, 0), edge("B", "A", 3, 0), edge("A", "C", 2), edge("A", "T", 2, 5, -65), edge("B", "C", 3, 3), edge("C", "T", 4)],
    source: "S", supply: 8, budget: 36, costGoal: 26, efficient: 24,
    reference: [route("SACT", 2), route("SBAT", 2), route("SBCT", 2)],
    hints: ["每条路线仍要逐段加费，南站到北站的箭头只朝一个方向。", "桥头到河岸最多 4 箱，另外 2 箱要走北站直达通道。总仓到南站免费。", "总仓经北站、桥头送 2 箱；经南站、北站直达送 2 箱；经南站、桥头送 2 箱。费用 24 点。"],
    recap: "方向决定路线能否走通，费用要逐段相加，地图上的远近不参与这笔账。",
  },
  {
    id: 11, title: "堵在山腰的七箱", concept: "内部瓶颈 · 上限证明",
    opening: "总仓有 15 箱，河岸站这班要 7 箱。周姨问能不能再送，许衡请你留下路线与分界：“把这 7 箱送齐，再证明路网的上限，下一班好按这个数备货。”",
    places: crossing(7),
    edges: [edge("S", "A", 8), edge("S", "B", 7), edge("A", "C", 3), edge("B", "C", 2), edge("B", "D", 2, 3), edge("C", "D", 3, 0), edge("D", "T", 6), edge("C", "T", 4, 2)],
    source: "S", supply: 15, budget: 40, efficient: 27, certificate: true,
    reference: [route("SACDT", 3), route("SBCT", 2), route("SBDT", 2)], referenceCut: ["S", "A", "B"],
    hints: ["不要只检查总仓出口或河岸入口。山腰的通道也可能限制整班运输。", "北站、南站到两处桥头的容量合计 3 + 2 + 2 = 7 箱。", "北站经上桥头、下桥头送 3 箱；南站经上桥头送 2 箱，经下桥头送 2 箱。勾选总仓、北站、南站，分界 7 箱，费用 27 点。"],
    recap: "把限制运输的中间通道划在分界上，也能证明整张路网的上限。",
  },
  {
    id: 12, title: "分界上的回程箭头", concept: "割容量 · 跨入与跨出",
    opening: "桥头站有一条朝北站的单向通道，许衡特地圈出箭头。河岸站要 5 箱，请送齐并留下上限证明。总仓有 9 箱，预算 30 点，完整方向和容量都在表里。",
    places: fork(5),
    edges: [edge("S", "A", 5), edge("S", "B", 4), edge("A", "C", 2), edge("B", "C", 3, 2), edge("C", "T", 8), edge("C", "A", 4, 0, -60)],
    source: "S", supply: 9, budget: 30, efficient: 18, certificate: true,
    reference: [route("SACT", 2), route("SBCT", 3)], referenceCut: ["S", "A", "B"],
    hints: ["给地点分组后，逐条看箭头从哪一组出发。只有从总仓侧跨出的容量计入上限。", "把总仓、北站、南站放在一组，跨出到桥头的容量为 2 + 3。桥头回北站的 4 箱不计入这个和。", "经北站、桥头送 2 箱，经南站、桥头送 3 箱；勾选总仓、北站、南站。送达与分界都是 5 箱，费用 18 点。"],
    recap: "割容量只加从总仓侧跨出的通道，跨回总仓侧的箭头不能加进去。",
  },
  {
    id: 13, title: "北站的旧草案", concept: "独立改排 · 腾出容量",
    opening: "夜班留下 4 箱未发的草案：总仓经北站、南站送到河岸站。周姨现在要 8 箱。许衡让你接手：“还没发货，路线和箱数都能改。把这一班送齐。”",
    places: [place("S", "总仓", 10, 50), place("A", "北站", 44, 20), place("B", "南站", 44, 80), receiver("T", "河岸站", 50, 8)],
    edges: [edge("S", "A", 4), edge("S", "B", 4, 2), edge("A", "B", 4, 0), edge("A", "T", 4, 2), edge("B", "T", 4)],
    source: "S", supply: 8, budget: 32, efficient: 24, seed: [route("SABT", 4)],
    reference: [route("SAT", 4), route("SBT", 4)],
    hints: ["已有草案占满了总仓到北站、南站到河岸。先检查换一条路线能空出哪些通道。", "北站有直达河岸的通道。旧路线改走这里，就能把南站到河岸的容量留给另一批箱子。", "点旧路线旁的“改排”，改为总仓 → 北站 → 河岸站 4 箱并保存，再经南站安排 4 箱。总费用 24 点。"],
    recap: "还没执行的计划可以重排，撤回一段共享通道能让另一条路线继续送货。",
  },
  {
    id: 14, title: "绕过两站的单子", concept: "路线改排 · 释放共用通道",
    opening: "上一班排了 4 箱，经北站、上桥头、南站、下桥头去河岸站。周姨需要 8 箱，草案还未执行。许衡把旧单留给你，允许重新排路线，费用预算为 44 点。",
    places: crossing(8),
    edges: [edge("S", "A", 4), edge("S", "B", 4, 2), edge("A", "C", 4), edge("C", "B", 4, 0, -35), edge("B", "D", 4), edge("D", "T", 4), edge("A", "T", 4, 4, 65)],
    source: "S", supply: 8, budget: 44, efficient: 36, seed: [route("SACBDT", 4)],
    reference: [route("SAT", 4), route("SBDT", 4)],
    hints: ["旧路线经过多个中转站，可能占了另一批箱子需要的通道。比较改排前后哪些容量会空出来。", "北站直达河岸后，旧路线在上桥头、南站和下桥头的占用都会释放。南站就能接总仓送来的另一批箱子。", "点旧路线旁的“改排”，改为总仓 → 北站 → 河岸站 4 箱并保存。再安排总仓 → 南站 → 下桥头 → 河岸站 4 箱，共 36 点。"],
    recap: "一条旧路线改走其他通道，能同时空出原来多段通道的容量。",
  },
  {
    id: 15, title: "两个桥头的分工", concept: "共同通道 · 费用取舍",
    opening: "河岸站要 7 箱，山脚站要 6 箱，坡口站也能转运了。许衡送来这班的收费表：“有些通道免费，但出口有限。两站都要收齐，运费控制在 38 点以内。”",
    places: district(7, 6).filter(p => p.id !== "F"),
    edges: [edge("S", "A", 5), edge("S", "B", 5), edge("S", "C", 4, 2), edge("A", "D", 4, 0), edge("A", "E", 3, 2), edge("B", "D", 3, 0), edge("B", "E", 4), edge("C", "E", 4, 0), edge("D", "T", 5), edge("D", "U", 4, 2), edge("E", "T", 2, 2), edge("E", "U", 4)],
    source: "S", supply: 14, budget: 48, costGoal: 38, efficient: 36,
    reference: [route("SADT", 4), route("SBDT", 1), route("SBDU", 2), route("SBET", 2), route("SCEU", 4)],
    hints: ["把两站入口与每个桥头的共用通道一起看。先送齐一站，可能让另一站只能走昂贵路线。", "上桥头到河岸最多 5 箱，中桥头到河岸最多 2 箱，这两个入口都要用满。", "北站经上桥头到河岸 4 箱；南站经上桥头到河岸 1 箱、到山脚 2 箱，经中桥头到河岸 2 箱；坡口经中桥头到山脚 4 箱。共 36 点。"],
    recap: "出口容量决定两站至少各走哪些通道，再比较上游怎么分配才省费用。",
  },
  {
    id: 16, title: "学校也要四箱", concept: "三站需求 · 容量分配",
    opening: "学校加入这一班，河岸站、山脚站和学校各要 4 箱。三处桥头通向不同接收站，许衡把需求全写在地图旁：“各站分别清点，哪边多收都不能抵掉另一边少的。”",
    places: district(4, 4, 4),
    edges: [edge("S", "A", 5), edge("S", "B", 5), edge("S", "C", 4, 2), edge("A", "D", 4, 0), edge("A", "E", 2, 2), edge("B", "D", 3), edge("B", "E", 3, 0), edge("B", "F", 2, 2), edge("C", "E", 2), edge("C", "F", 3, 0), edge("D", "T", 4), edge("D", "U", 3, 0), edge("E", "T", 2, 2), edge("E", "U", 3), edge("E", "V", 2, 0), edge("F", "U", 2, 2), edge("F", "V", 3)],
    source: "S", supply: 14, budget: 40, costGoal: 28, efficient: 26,
    reference: [route("SADT", 3), route("SADU", 1), route("SAET", 1), route("SBDU", 2), route("SBEU", 1), route("SBEV", 2), route("SCFV", 2)],
    hints: ["先分别核对三站可用的入口，再加总上游共享通道的占用。", "学校可从中桥头和下桥头收货。中桥头的免费出口值得比较，但同一批箱子不能同时交给山脚站。", "北站经上桥头给河岸 3 箱、山脚 1 箱，经中桥头给河岸 1 箱；南站经上桥头给山脚 2 箱，经中桥头给山脚 1 箱、学校 2 箱；坡口经下桥头给学校 2 箱。共 26 点。"],
    recap: "接收点增加后，仍要分别满足需求，并合计每段通道上来自不同路线的箱数。",
  },
  {
    id: 17, title: "十三箱的交班证明", concept: "最大流 · 费用规划",
    opening: "周姨要 13 箱，运输站还要留一份路网能力证明。许衡把所有转运口的容量与报价送齐：总仓有 21 箱，预算 60 点，交班费用不超过 47 点。请独立安排。",
    places: district(13),
    edges: [edge("S", "A", 8), edge("S", "B", 7), edge("S", "C", 6, 2), edge("A", "D", 5), edge("A", "E", 3, 2), edge("B", "D", 4), edge("B", "E", 3), edge("C", "F", 4), edge("C", "E", 2, 0), edge("D", "T", 5), edge("E", "T", 4, 2), edge("F", "T", 4), edge("D", "E", 2, 0), edge("E", "F", 2, 0)],
    source: "S", supply: 21, budget: 60, costGoal: 47, efficient: 45, certificate: true,
    reference: [route("SADT", 5), route("SBDET", 1), route("SBET", 3), route("SCFT", 2), route("SCEFT", 2)], referenceCut: ["S", "A", "B", "C", "D", "E", "F"],
    hints: ["找到运力上限以后，还要比较达到这个运量的不同费用。箱数证明与费用目标分别核对。", "河岸三个入口合计 5 + 4 + 4 = 13 箱。桥头之间的免费转运会改变上游的分配。", "北站经上桥头送 5 箱；南站经上、中桥头送 1 箱，经中桥头送 3 箱；坡口经下桥头送 2 箱，经中、下桥头送 2 箱。勾选除河岸外全部地点，共 45 点。"],
    recap: "送达量等于割容量能证明最大流，达到这个运量的费用仍需要单独比较。",
  },
  {
    id: 18, title: "分界移到桥前", concept: "内部最小割 · 全网核对",
    opening: "河岸站这班要 14 箱，几处桥头的出口扩宽了。许衡请你重新核对上限：“旧分界未必还是最小，按今天的容量来。”总仓有 24 箱，运费目标为 46 点。",
    places: district(14),
    edges: [edge("S", "A", 9), edge("S", "B", 8, 0), edge("S", "C", 7, 2), edge("A", "D", 4), edge("A", "E", 2, 0), edge("B", "D", 3, 2), edge("B", "F", 2), edge("C", "E", 2), edge("C", "F", 1, 0), edge("D", "T", 7), edge("E", "T", 6, 2), edge("F", "T", 6)],
    source: "S", supply: 24, budget: 60, costGoal: 46, efficient: 44, certificate: true,
    reference: [route("SADT", 4), route("SAET", 2), route("SBDT", 3), route("SBFT", 2), route("SCET", 2), route("SCFT", 1)], referenceCut: ["S", "A", "B", "C"],
    hints: ["沿途每层通道都要检查，入口扩宽并不代表全网能力同样增加。", "总仓出口合计 24 箱，河岸入口合计 19 箱；三处转运站到桥头的通道合计只有 14 箱。", "北站经上桥头 4 箱、中桥头 2 箱；南站经上桥头 3 箱、下桥头 2 箱；坡口经中桥头 2 箱、下桥头 1 箱。勾选总仓、北站、南站、坡口，分界 14 箱，费用 44 点。"],
    recap: "分界要按当前容量重新选择，瓶颈可能在中间一层，而非接收站入口。",
  },
  {
    id: 19, title: "街区合用三座桥", concept: "整班调度 · 两站与费用",
    opening: "雨后的分发量增加了，河岸站要 8 箱，山脚站要 7 箱。许衡去核对下一班库存，这班的路线交给你：总仓有 18 箱，运费不超过 43 点。",
    places: district(8, 7),
    edges: [edge("S", "A", 7), edge("S", "B", 6), edge("S", "C", 5, 2), edge("A", "D", 5, 0), edge("A", "E", 4, 2), edge("B", "D", 4), edge("B", "E", 3, 0), edge("B", "F", 3, 2), edge("C", "E", 3), edge("C", "F", 4, 0), edge("D", "T", 6), edge("D", "U", 3, 2), edge("E", "T", 4, 2), edge("E", "U", 4), edge("F", "T", 2, 4), edge("F", "U", 4)],
    source: "S", supply: 18, budget: 58, costGoal: 43, efficient: 41,
    reference: [route("SADT", 5), route("SAET", 2), route("SBDT", 1), route("SBEU", 3), route("SCFU", 4)],
    hints: ["各站有多种入口，先比较每箱总费用，再核对分配后的上游容量。", "坡口到下桥头免费，下桥头到山脚每箱 1 点；北站到上桥头也免费，但出口要与其他路线合计。", "北站经上桥头给河岸 5 箱、经中桥头给河岸 2 箱；南站经上桥头给河岸 1 箱、经中桥头给山脚 3 箱；坡口经下桥头给山脚 4 箱。共 41 点。"],
    recap: "低价通道的价值取决于整条路线和共享容量，单段免费不能替代整班核算。",
  },
  {
    id: 20, title: "报价换了的一班", concept: "费用变化 · 重新分配",
    opening: "南站出仓通道今天免费，桥头收费却换了。河岸站要 10 箱，山脚站要 8 箱。许衡留下新的完整报价，请你安排这班，运费最多 49 点。",
    places: district(10, 8),
    edges: [edge("S", "A", 8), edge("S", "B", 7, 0), edge("S", "C", 6, 2), edge("A", "D", 5), edge("A", "E", 4, 0), edge("B", "D", 4, 0), edge("B", "E", 3, 2), edge("B", "F", 3), edge("C", "E", 3), edge("C", "F", 5, 0), edge("D", "T", 6, 2), edge("D", "U", 3), edge("E", "T", 4), edge("E", "U", 4, 2), edge("F", "T", 3, 4), edge("F", "U", 5)],
    source: "S", supply: 21, budget: 65, costGoal: 49, efficient: 47,
    reference: [route("SADT", 4), route("SAET", 4), route("SBDT", 1), route("SBDU", 3), route("SBFT", 1), route("SBFU", 2), route("SCFU", 3)],
    hints: ["按本章报价重新加总每条路线，别直接沿用上一班分配。", "河岸需 10 箱，中桥头入口只有 4 箱，上桥头入口只有 6 箱；南站还要给山脚分配出口。", "北站经上桥头、中桥头给河岸各 4 箱；南站经上桥头给河岸 1 箱、山脚 3 箱，经下桥头给河岸 1 箱、山脚 2 箱；坡口经下桥头给山脚 3 箱。共 47 点。"],
    recap: "需求和报价改变后，原有的低费分配也要重新比较，容量合计仍按整班检查。",
  },
  {
    id: 21, title: "三处同时开饭", concept: "三站交付 · 共用容量",
    opening: "河岸站要 7 箱，山脚站要 6 箱，学校要 5 箱。各处按收到的补给准备午饭。许衡把本班地图留在桌上，运费控制在 47 点以内，由你安排并确认发货。",
    places: district(7, 6, 5),
    edges: [edge("S", "A", 8), edge("S", "B", 7), edge("S", "C", 6, 2), edge("A", "D", 5, 0), edge("A", "E", 4), edge("B", "D", 4, 2), edge("B", "E", 4, 0), edge("B", "F", 3), edge("C", "E", 3), edge("C", "F", 5, 0), edge("D", "T", 5), edge("D", "U", 4, 0), edge("E", "T", 3, 2), edge("E", "U", 4), edge("E", "V", 3, 0), edge("F", "U", 3, 2), edge("F", "V", 5)],
    source: "S", supply: 21, budget: 65, costGoal: 47, efficient: 45,
    reference: [route("SADT", 4), route("SADU", 1), route("SAET", 3), route("SBDU", 3), route("SBEU", 2), route("SBEV", 2), route("SCEV", 1), route("SCFV", 2)],
    hints: ["逐站看入口，整班看上游。三站总量够了也要检查分别收到了多少。", "上桥头可以免费送山脚，中桥头可以免费送学校，但河岸仍需要从这两处收货。", "北站经上桥头给河岸 4 箱、山脚 1 箱，经中桥头给河岸 3 箱；南站经上桥头给山脚 3 箱，经中桥头给山脚、学校各 2 箱；坡口经中桥头给学校 1 箱、经下桥头给学校 2 箱。共 45 点。"],
    recap: "一处的免费出口会影响其他接收站能分到的容量，三份需求必须一起规划。",
  },
  {
    id: 22, title: "晚班需求对调", concept: "需求变化 · 路线重排",
    opening: "晚班名单改了：河岸站 6 箱、山脚站 9 箱、学校 7 箱。今天的容量和费用都已更新，总仓有 24 箱。许衡请你留好每条路线，整班运费不超过 51 点。",
    places: district(6, 9, 7),
    edges: [edge("S", "A", 9), edge("S", "B", 8, 0), edge("S", "C", 7, 2), edge("A", "D", 6), edge("A", "E", 4, 0), edge("B", "D", 4, 0), edge("B", "E", 5, 2), edge("B", "F", 4), edge("C", "E", 3), edge("C", "F", 6, 0), edge("D", "T", 6), edge("D", "U", 4, 0), edge("E", "T", 3, 2), edge("E", "U", 6), edge("E", "V", 3, 0), edge("F", "U", 4, 2), edge("F", "V", 6)],
    source: "S", supply: 24, budget: 70, costGoal: 51, efficient: 49,
    reference: [route("SADT", 5), route("SAEU", 4), route("SBDT", 1), route("SBDU", 3), route("SBFU", 2), route("SBFV", 2), route("SCEV", 3), route("SCFV", 2)],
    hints: ["先按新需求核对每站，再比较调整后每段路的占用。旧方案总量与各站数量都可能不合适。", "山脚要 9 箱，需要多个桥头共同供货。南站的免费出仓通道最多 8 箱，它的三个出口要合计。", "北站经上桥头给河岸 5 箱、经中桥头给山脚 4 箱；南站经上桥头给河岸 1 箱、山脚 3 箱，经下桥头给山脚、学校各 2 箱；坡口经中桥头给学校 3 箱、经下桥头给学校 2 箱。共 49 点。"],
    recap: "需求换了位置，容量与费用的分配也会改变，不能只调整运输总箱数。",
  },
  {
    id: 23, title: "冷库加入交班单", concept: "四站运输 · 整班取舍",
    opening: "冷库加入配送，街口站也接上了路网。河岸站要 6 箱、山脚站 7 箱、学校 6 箱、冷库 5 箱。许衡已备齐 25 箱，完整通道表在桌上，交班运费不超过 58 点。",
    places: district(6, 7, 6, 5),
    edges: [edge("S", "A", 9), edge("S", "B", 8), edge("S", "C", 8, 2), edge("A", "D", 6), edge("A", "E", 4, 0), edge("A", "F", 2, 3, -40), edge("B", "D", 3, 0), edge("B", "E", 5, 2), edge("B", "F", 5, 0), edge("C", "E", 3), edge("C", "F", 4, 2), edge("C", "G", 6), edge("D", "T", 6, 2), edge("D", "U", 4, 0), edge("E", "T", 4, 0), edge("E", "U", 5, 2), edge("E", "V", 4, 3), edge("F", "U", 4), edge("F", "V", 6, 0), edge("F", "W", 3, 4), edge("G", "T", 3, 4, 75), edge("G", "V", 3, 2), edge("G", "W", 5, 0)],
    source: "S", supply: 25, budget: 80, costGoal: 58, efficient: 56,
    reference: [route("SADT", 2), route("SADU", 1), route("SAET", 4), route("SAFV", 1), route("SBDU", 3), route("SBFV", 5), route("SCEU", 3), route("SCGW", 5)],
    hints: ["四站分别核对，出仓、桥头与接收站入口都可能限制选择。每条路线仍按全部路段加费。", "冷库的街口入口免费，但总仓到坡口每箱 2 点；学校与山脚还要分用下桥头。", "北站经上桥头给河岸 2 箱、山脚 1 箱，经中桥头给河岸 4 箱、经下桥头给学校 1 箱；南站经上桥头给山脚 3 箱、经下桥头给学校 5 箱；坡口经中桥头给山脚 3 箱、经街口给冷库 5 箱。共 56 点。"],
    recap: "接收站更多时，便宜通道之间也会争用上游容量，费用要按完整计划比较。",
  },
  {
    id: 24, title: "山城的整班交接", concept: "独立调度 · 四站综合运输",
    opening: "运输站今天由你交班。河岸站要 8 箱、山脚站 9 箱、学校 7 箱、冷库 8 箱，总仓备了 34 箱。夜班留下两条未发草案，你可以修改或重新安排。所有方向、容量与每箱费用已列齐；本班预算 100 点，交班运费不超过 68 点。请把四处补给送齐，再留下完整路线。",
    places: district(8, 9, 7, 8),
    edges: [edge("S", "A", 12), edge("S", "B", 11), edge("S", "C", 11, 2), edge("A", "D", 8), edge("A", "E", 7, 0), edge("A", "F", 4, 3, -40), edge("B", "D", 4, 0), edge("B", "E", 7, 2), edge("B", "F", 6, 0), edge("C", "E", 4), edge("C", "F", 6, 2), edge("C", "G", 8), edge("D", "T", 8, 0), edge("D", "U", 5, 0), edge("E", "T", 7, 0), edge("E", "U", 7, 2), edge("E", "V", 5, 3), edge("F", "U", 6), edge("F", "V", 7, 0), edge("F", "W", 4, 4), edge("G", "T", 4, 4, 75), edge("G", "V", 4, 2), edge("G", "W", 8, 0)],
    source: "S", supply: 34, budget: 100, costGoal: 68, efficient: 66, seed: [route("SADT", 4), route("SBEU", 3)],
    reference: [route("SADT", 4), route("SADU", 1), route("SAET", 4), route("SAEU", 3), route("SBDU", 4), route("SBEU", 1), route("SBFV", 6), route("SCFV", 1), route("SCGW", 8)],
    hints: ["先核对四站入口，再比较完整路线的费用。旧草案还没发货，若占掉另一份安排需要的通道，可以改箱数、改排路线或删除路线。", "北站到中桥头、南站到下桥头都免费，但出仓容量仍有限。上桥头到山脚最多 5 箱，街口到冷库最多 8 箱；这几处要和河岸、学校的路线一起分配。", "将草案改为：北站经上桥头给河岸 4 箱、山脚 1 箱，经中桥头给河岸 4 箱、山脚 3 箱；南站经上桥头给山脚 4 箱、经中桥头给山脚 1 箱、经下桥头给学校 6 箱；坡口经下桥头给学校 1 箱、经街口给冷库 8 箱。四站收到 8、9、7、8 箱，费用 66 点。"],
    recap: "完整调度要同时满足各站需求、共享容量和费用目标，旧草案也要放进整班计划重新核对。",
  },
];
