import { seededRandom, STANDARD_CODES } from "./engine.js";
import type { Counts, Lesson, Mission, Noise, Packet } from "./types.js";

function tokens(counts: Counts, seed: string) {
  const bag = Object.entries(counts).flatMap(([id, n]) => Array(n).fill(id));
  const random = seededRandom(seed);
  for (let i = bag.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [bag[i], bag[j]] = [bag[j], bag[i]];
  }
  return bag;
}

function packet(id: string, name: string, counts: Counts, deadline = 1, extra: Partial<Packet> = {}): Packet {
  return { id, name, tokens: tokens(counts, id), deadline, required: true, priority: "常规", description: "导航指令", ...extra };
}

const normal = { A: 8, B: 4, C: 2, D: 2 };
const skewed = { A: 10, B: 3, C: 2, D: 1 };
const changed = { A: 2, B: 2, C: 4, D: 8 };
const quiet: Noise = { type: "none", label: "清洁信道", detail: "没有比特翻转，可专注于编码长度。", strength: 0 };
const single: Noise = { type: "single", label: "单次脉冲", detail: "每个消息包恰有 1 个比特翻转。", strength: 1 };
const blocks: Noise = { type: "blocks", blockSize: 7, label: "周期干扰", detail: "按消息包划分，每个连续 7 比特码块恰有 1 位翻转；末尾不足 7 位的块也翻转 1 位。", strength: 2 };

export const MISSIONS: Mission[] = [
  {
    id: 1, chapter: "建立连接", title: "给信使号发送进站航线", destination: "信使号",
    kicker: "FIRST CONTACT", concept: "比特与码字", budget: 32, rounds: 1, parBits: 32,
    noise: quiet, protections: ["none"],
    packets: [packet("first", "信使号导航请求", normal, 1, { description: "艾拉正在等待进站航线。这里有 16 条导航指令。" })],
    objective: "在 32 bit 预算内，正确发送全部 16 条指令。",
    briefing: "信使号正在等待进站航线。四种指令各用 2 位二进制码字表示，接收端已备好同一码本。选中导航请求，检查长度后发送。",
    hint: "4 种指令可以用 00、01、10、11 区分。16 条指令 × 2 bit = 32 bit，刚好装满本轮信道。",
    takeaway: "这套定长码用 2 bit 区分四种指令。接收端每读两位，就能还原一条指令。",
    lesson: "bits", accent: "mint",
  },
  {
    id: 2, chapter: "每比特都珍贵", title: "给常见指令分配短码字", destination: "信使号",
    kicker: "SOURCE CODING", concept: "前缀码与信息熵", budget: 28, rounds: 1, parBits: 28,
    noise: quiet, protections: ["none"],
    packets: [packet("compression", "巡航路线更新", normal)],
    objective: "把原本 32 bit 的指令压缩到 28 bit，并完整解码。",
    briefing: "太阳能阵列需要维修，本轮只能发 28 bit。“前进”占了指令的一半，可以给它用短码字。切换到变长编码，试着构造一棵码树。",
    hint: "打开“构造码树”，先合并权重最小的两项，再重复这一操作。叶子路径上的 0、1 就是码字。",
    takeaway: "指令频率越不均匀，通常越有压缩空间。前缀码让接收端能分清码字边界。本关 H = 1.75 bit/指令，哈夫曼平均码长也是 1.75。",
    lesson: "prefix", accent: "mint",
  },
  {
    id: 3, chapter: "读懂消息源", title: "航线改变，码本也要改变", destination: "织女航道",
    kicker: "ENTROPY SHIFT", concept: "哈夫曼编码", budget: 25, rounds: 1, parBits: 25,
    noise: quiet, protections: ["none"],
    packets: [packet("skew", "长距离巡航指令", skewed)],
    objective: "利用新的出现频率，将 16 条指令控制在 25 bit。",
    briefing: "飞船进入长直线航段，“前进”比上一段更多。按消息队列里的新频率重新配置码本，看看能省下多少位。",
    hint: "前进 10 次、左转 3 次、右转 2 次、停止 1 次。哈夫曼自动工具已解锁，也可以手工实验。",
    takeaway: "哈夫曼编码最小化逐符号二进制前缀码的平均长度。熵是理论下界，受码长必须取整数的限制，平均码长不总能等于熵。",
    lesson: "entropy", accent: "blue",
  },
  {
    id: 4, chapter: "噪声来袭", title: "信号抵达，消息却变了", destination: "碎石带前哨",
    kicker: "NOISY CHANNEL", concept: "冗余与重复码", budget: 24, rounds: 1, parBits: 24,
    noise: single, protections: ["none", "repeat"],
    packets: [packet("pulse", "前哨紧急避障", { A: 1, B: 1, C: 1, D: 1 }, 1, { priority: "紧急", description: "必须准确执行，任意一条错误都会造成航线偏移。" })],
    objective: "抵抗一次比特翻转，准确交付全部 4 条指令。",
    briefing: "电磁脉冲会让消息中的一位比特翻转。原始数据有 8 bit，直接发送可能变成错误指令。把每位发三遍，接收端就能用多数票恢复它。",
    hint: "三次重复把 0 变成 000、1 变成 111。一个三元组内至多出错一位时，多数票能恢复原比特，传输成本是 3 倍。",
    takeaway: "三次重复能纠正每组三位中的一个错误，发送量增加到三倍。选保护方式时，要检查干扰是否在它的纠错范围内。",
    lesson: "repeat", accent: "gold",
  },
  {
    id: 5, chapter: "给冗余安排位置", title: "用三位校验保护四位数据", destination: "卡西尼观测站",
    kicker: "ERROR CORRECTION", concept: "汉明 (7,4) 码", budget: 56, rounds: 1, parBits: 56,
    noise: blocks, protections: ["none", "repeat", "hamming"],
    packets: [packet("hamming", "观测站姿态校准", normal)],
    objective: "在 56 bit 内，抵抗每个 7 比特码块的一位错误。",
    briefing: "这次每个 7 位传输块都会错一位，三次重复需要 96 bit，超出预算。汉明码给每 4 位数据加 3 位校验，利用校验结果找出单个错误。",
    hint: "打开“纠错实验台”，手动翻转一位，观察校验综合值如何指出位置。再选择汉明 (7,4) 发送。",
    takeaway: "普通汉明 (7,4) 码能纠正一个码块中的单比特错误；遇到多比特错误可能误纠正，它不能可靠识别所有双错。",
    lesson: "hamming", accent: "blue",
  },
  {
    id: 6, chapter: "联合设计", title: "在有限空间里发对导航指令", destination: "欧罗巴救援舰",
    independent: true, difficulty: "首次考核",
    kicker: "COMPRESSION × CORRECTION", concept: "压缩与纠错协同", budget: 52, rounds: 1, parBits: 49,
    noise: blocks, protections: ["none", "repeat", "hamming"],
    packets: [packet("rescue-link", "救援舰精密导航", normal, 1, { priority: "紧急", description: "救援舰靠港需要精确导航。消息既要装得下，也要抵抗干扰。" })],
    objective: "在 52 bit 内同时完成压缩、纠错和准确交付。",
    briefing: "值班长暂时离开席位。三种保护和两种编码你都试过了，这次自己组合。先查看干扰和预算，算好发送成本；方案是否有效，要看发送后的结果。",
    hint: "32 bit → 哈夫曼编码 28 bit → 7 个汉明码块 × 7 bit = 49 bit。",
    hints: ["检查两件事：消息能否装进预算，干扰能否被纠正。分别考虑哪个工具能解决它。", "按所选消息的频率设计码本，再检查加上保护后的总长度。", "根据消息频率生成哈夫曼码，再选择汉明保护。28 位数据保护后为 49 bit。"],
    takeaway: "信源编码按统计规律缩短数据，信道编码加入纠错冗余。本关先压缩再加保护，总计 49 bit。",
    lesson: "joint", accent: "mint",
  },
  {
    id: 7, chapter: "通信官的抉择", title: "消息都有期限，带宽只有一份", destination: "天琴座舰队",
    independent: true, difficulty: "调度考核",
    kicker: "MISSION SCHEDULING", concept: "预算与截止时间", budget: 35, rounds: 3, parBits: 56,
    noise: blocks, protections: ["none", "repeat", "hamming"],
    initialCoding: "custom", initialCodes: STANDARD_CODES, initialSelected: ["urgent"],
    packets: [
      packet("urgent", "救援舰避障指令", { A: 4, B: 2, C: 1, D: 1 }, 1, { priority: "紧急", description: "必须在第 1 轮结束前收到。", value: 60 }),
      packet("repair", "空间站维修导航", { A: 2, B: 1, C: 0, D: 1 }, 2, { description: "第 2 轮结束前交付。", value: 25 }),
      packet("survey", "探测器扫描航线", { A: 2, B: 1, C: 1, D: 0 }, 3, { description: "最晚可在第 3 轮交付。", value: 15 }),
    ],
    objective: "按时交付全部 3 个任务。每轮预算独立，不结转。",
    briefing: "三条请求同时到了，救援舰最早到期，维修和扫描可以稍后处理。查看各包加上保护后的长度，安排每轮的发送顺序。",
    hint: "用现有码本加汉明保护：救援 28 bit，维修 14 bit，扫描 14 bit。第一轮无法三条都发，第二轮可以一起发送后两条。",
    hints: ["先看所有请求的截止时间，再选本轮消息。任务优先级和指令频率要分别考虑。", "各消息包独立补位。期限最早的请求必须在本轮交付，不能等到下一轮。", "沿用初始码本并选择汉明保护：第 1 轮只发救援 28 bit；第 2 轮合发维修和扫描 28 bit。共 56 bit。"],
    takeaway: "消息的任务价值与信息熵是不同的概念。熵衡量不确定性，截止时间和优先级来自任务本身。",
    lesson: "schedule", accent: "gold",
  },
  {
    id: 8, chapter: "独立值守", title: "为不同航线安排码本", destination: "边境探索舰队",
    independent: true, difficulty: "综合考核",
    kicker: "FINAL SHIFT", concept: "动态码本与同步成本", budget: 65, rounds: 3, parBits: 178,
    noise: blocks, protections: ["none", "repeat", "hamming"],
    initialCoding: "custom", initialCodes: STANDARD_CODES, receiverCodes: STANDARD_CODES,
    initialProtection: "hamming", initialSelected: ["frontier"], syncCost: 12,
    packets: [
      packet("frontier", "探索舰紧急制动序列", changed, 1, { priority: "紧急", description: "“停止”变成最常见指令；第 1 轮必须送达。", value: 60 }),
      packet("dock", "货运舰靠港指令", { A: 1, B: 1, C: 2, D: 4 }, 2, { description: "新分布，第 2 轮到期。", value: 20 }),
      packet("escort", "护航舰编队指令", { A: 1, B: 1, C: 2, D: 4 }, 2, { description: "新分布，第 2 轮到期。", value: 20 }),
      packet("archive", "旧航线档案回传", normal, 3, { required: false, priority: "额外任务", description: "仍以“前进”为主，完成它才能获得三星。", value: 15 }),
    ],
    objective: "完成 3 个必要任务；额外交付旧航线档案，挑战三星。",
    briefing: "接收端还在用旧码本，几条待发请求的指令分布各不相同。更新码字要先发 12 bit 的可靠同步帧。比较压缩收益和同步费用时，也看看后续请求的频率与期限。",
    hint: "第一轮按紧急消息重新生成码本：49 + 12 = 61 bit。第二轮合发靠港与护航：56 bit。第三轮为旧档案换回适合它的码本：49 + 12 = 61 bit。",
    hints: ["先对照接收端码本。只要实际码字有变化，本轮就要支付同步费用。", "选中本轮消息后再查看频率，后面的请求可能需要另一套码本。", "第 1 轮制动哈夫曼 + 汉明，含同步 61。第 2 轮沿用码本，合发靠港与护航 56。第 3 轮为档案生成哈夫曼码，含同步 61。总计 178 bit。"],
    takeaway: "码本是通信双方共享的协议。压缩收益需要扣除同步成本；消息分布变化时，应结合未来发送量决定是否更新。",
    lesson: "sync", accent: "pink",
  },
  {
    id: 9, chapter: "短码的代价", title: "数据更短，为什么反而发不下？", destination: "双子无人站",
    independent: true, difficulty: "进阶 · 分包成本",
    kicker: "PACKET GRANULARITY", concept: "哈夫曼的优化边界", budget: 21, rounds: 1, parBits: 21,
    noise: blocks, protections: ["none", "repeat", "hamming"], initialSelected: [],
    packets: [
      packet("micro-stop", "停机确认", { A: 0, B: 0, C: 0, D: 2 }, 1, { description: "两条停止指令。必须独立成包，不能与另一个请求合并。", priority: "紧急" }),
      packet("micro-route", "姿态修正", { A: 1, B: 1, C: 1, D: 1 }, 1, { description: "四种指令各一次。两条请求共用本轮码本，但分别补位和保护。" }),
    ],
    objective: "同一轮准确交付两个独立小包。完整发送不得超过 21 bit。",
    briefing: "自动编码缩短了数据，加上保护后却仍然超载。两个消息包必须分别发送、分别补位。查看分包成本，找出长度增加在哪一步。",
    hints: [
      "哈夫曼工具优化的是信源长度。本关预算计算每包单独补位、加保护后的总长度。",
      "在“调整通信方案”里展开分包成本，数一数每包需要几个 4 位数据块。定长码也符合前缀码的要求。",
      "两包都用定长编码和汉明保护：4 位 → 7 bit，8 位 → 14 bit，共 21 bit。对合计频率生成哈夫曼码会得到 2 位和 9 位，保护后共 28 bit。",
    ],
    hint: "检查每个消息包的补位成本，而不只看合计平均码长。",
    takeaway: "哈夫曼码让信源数据最短，但每包还要独立补位。小包多占一个码块，就可能抵消压缩省下的空间。",
    lesson: "granularity", accent: "gold",
  },
  {
    id: 10, chapter: "安静的一轮", title: "哪条请求需要安静窗口？", destination: "织女中继阵列",
    independent: true, difficulty: "进阶 · 信道窗口",
    kicker: "CHANNEL WINDOWS", concept: "择时与保护选择", budget: 28, rounds: 3, parBits: 70, totalBudget: 70,
    noise: blocks, protections: ["none", "repeat", "hamming"], initialSelected: [],
    initialCoding: "custom", initialCodes: STANDARD_CODES,
    windows: [
      { budget: 28, noise: blocks, label: "磁暴前沿" },
      { budget: 32, noise: quiet, label: "遮蔽区窗口" },
      { budget: 28, noise: blocks, label: "磁暴尾流" },
    ],
    packets: [
      packet("window-urgent", "先遣舰避障", { A: 4, B: 2, C: 1, D: 1 }, 1, { priority: "紧急", description: "第 1 轮必须抵达，不能等待遮蔽窗口。" }),
      packet("window-heavy", "中继阵列重置", normal, 3, { description: "指令最多的请求，第 3 轮截止。那时干扰会恢复。" }),
      packet("window-tail", "观测器航向", { A: 2, B: 1, C: 1, D: 0 }, 3, { description: "较短的请求，和重置消息竞争安静窗口。" }),
    ],
    objective: "三轮内交付全部请求；整次值班总成本不得超过 70 bit。",
    briefing: "三条请求都已抵达。第 2 轮没有干扰，其余两轮每 7 位翻转一位。结合期限和各轮容量排好队，再决定每轮的保护方式。",
    hints: [
      "看完三轮预报再排队。最晚截止的请求，不一定适合留到最后。",
      "重置消息加上保护后，装不进干扰窗口。只有一轮没有干扰，而且总预算小于三轮容量之和。",
      "沿用初始码本。第 1 轮：避障 + 汉明，28 bit。第 2 轮：重置 + 直接发送，28 bit。第 3 轮：航向 + 汉明，14 bit。共 70 bit。",
    ],
    hint: "预报是一部分任务条件；不要只根据当前轮的干扰作决定。",
    takeaway: "没有干扰时，直接发送可以省掉保护成本。大包即使截止较晚，也可能只有一个窗口能装下，需要提前为它留位置。",
    lesson: "windows", accent: "blue",
  },
  {
    id: 11, chapter: "留给下一条消息", title: "换码本前，先算下一轮", destination: "猎户航道",
    independent: true, difficulty: "进阶 · 协议承诺",
    kicker: "LOOK AHEAD", concept: "同步成本与前瞻", budget: 21, rounds: 2, parBits: 119, totalBudget: 119,
    noise: blocks, protections: ["none", "repeat", "hamming"], initialSelected: [],
    initialCoding: "custom", initialCodes: STANDARD_CODES, receiverCodes: STANDARD_CODES, initialProtection: "hamming", syncCost: 12,
    windows: [
      { budget: 21, noise: blocks, label: "短促回执" },
      { budget: 98, noise: blocks, label: "满载航线" },
    ],
    packets: [
      packet("commit-stop", "四次制动回执", { A: 0, B: 0, C: 0, D: 4 }, 1, { priority: "紧急", description: "当前只有停止指令。是否为它更新整套码本？" }),
      packet("commit-route", "后续长航线", { A: 16, B: 8, C: 4, D: 4 }, 2, { releaseRound: 2, description: "第 2 轮抵达。频率预报已经给出，但不能提前发送。" }),
    ],
    objective: "两轮均按期交付，整次值班不超过 119 bit。码本更新占 12 bit。",
    briefing: "当前回执全是“停止”，下一轮长航线则以“前进”为主。自动工具只按所选消息生成码本，接收端会沿用本轮码字。更新前，先算清两轮的数据、保护和同步费用。",
    hints: [
      "后续请求还没抵达，但频率和下一轮容量已经给出。本轮更新能省多少？下一轮再改要花多少？",
      "对照接收端码本，分别计算沿用与更新后的两轮总成本。自动工具只优化本轮选中的消息。",
      "保持原有码本和汉明保护。四次停止：12 位数据 → 21 bit；后续 32 条指令：56 位数据 → 98 bit，总计 119。第一轮更新虽然能降到 19 bit，第二轮却装不下改回协议的同步费。",
    ],
    hint: "把同步成本放到两轮一起计算。",
    takeaway: "本轮换码本省下的空间，可能小于下一轮改回时的同步费用。接收端会记住更新后的码字，后续发送也要按这套码本计算。",
    lesson: "lookahead", accent: "pink",
  },
  {
    id: 12, chapter: "最后一盏灯", title: "四个窗口，六条请求", destination: "弥拉边境网络",
    independent: true, difficulty: "进阶 · 综合规划",
    kicker: "THE LAST BEACON", concept: "全局成本与动态调度", budget: 42, rounds: 4, parBits: 164, totalBudget: 164,
    noise: blocks, protections: ["none", "repeat", "hamming"], initialSelected: [],
    initialCoding: "custom", initialCodes: STANDARD_CODES, receiverCodes: STANDARD_CODES, initialProtection: "hamming", syncCost: 12,
    windows: [
      { budget: 42, noise: blocks, label: "碎石带救援" },
      { budget: 38, noise: quiet, label: "第一段静区" },
      { budget: 61, noise: blocks, label: "边境磁暴" },
      { budget: 42, noise: quiet, label: "最后的回声" },
    ],
    packets: [
      packet("final-urgent", "救援艇避障", { A: 4, B: 2, C: 1, D: 1 }, 1, { priority: "紧急", description: "第 1 轮的必要救援。另有消息可以提前安排，但会消耗总预算。" }),
      packet("final-repair", "浮标修复导航", { A: 2, B: 1, C: 1, D: 0 }, 2, { description: "现在即可发送，第 2 轮到期。" }),
      packet("final-array", "阵列全量航线", normal, 2, { releaseRound: 2, description: "第 2 轮抵达，并在本轮结束前送达。" }),
      packet("final-brake", "探索舰制动序列", changed, 3, { releaseRound: 3, priority: "紧急", description: "第 3 轮抵达，停止指令占一半。" }),
      packet("final-home", "归航舰指令", { A: 4, B: 2, C: 1, D: 1 }, 4, { releaseRound: 4, description: "第 4 轮抵达，分布恢复为前进较多。" }),
      packet("final-memory", "无人站记忆档案", { A: 4, B: 2, C: 1, D: 1 }, 4, { required: false, priority: "额外任务", description: "现在已在队列里。完成它可保住无人站的记忆，并挑战三星。" }),
    ],
    objective: "四轮内交付五个必要请求，所有发送总计不超过 164 bit；额外保住无人站档案，挑战三星。",
    briefing: "林岚去修馈线，你来接管通信。请求的抵达轮次、频率、期限和信道预报都已给出。整次值班只能发送 164 bit，每轮也有容量限制。先排好四轮计划，再开始发送。",
    hints: [
      "先找出必须当轮交付的请求，再安排适合无干扰窗口的消息。提前发送也会消耗总预算。",
      "重点检查第 2 轮的容量和第 3 轮的码本。档案截止较晚，试着算算它和归航消息一起发送时的同步成本。",
      "沿用原码本：第 1 轮避障 + 汉明 28；第 2 轮修复与阵列 + 直接发送 35。第 3 轮只选制动、哈夫曼 + 汉明，含同步 61。第 4 轮选归航与档案，恢复原码本 + 直接发送，含同步 40。总计 164 bit。",
    ],
    hint: "不要急着发完第一轮的所有可发请求。先规划完整四轮。",
    takeaway: "每轮都要计入数据、保护、补位和同步成本，也要为后续请求留够总预算。完成所有必要请求后，还可以检查档案是否交付、总成本是否达到三星目标。",
    lesson: "lookahead", accent: "gold",
  },
  {
    id: 13, chapter: "接通返航线", title: "小回执和长航线共用一副天线", destination: "边境返航编队",
    independent: true, difficulty: "高难 · 混合保护",
    kicker: "RETURN CHANNEL", concept: "小包保护与协议衔接", budget: 6, rounds: 4, parBits: 134, totalBudget: 134,
    noise: single, protections: ["none", "repeat", "hamming"], initialSelected: [],
    initialCoding: "custom", initialCodes: { A: "110", B: "111", C: "10", D: "0" },
    receiverCodes: { A: "110", B: "111", C: "10", D: "0" }, syncCost: 12,
    windows: [
      { budget: 6, noise: single, label: "两次停机回执" },
      { budget: 61, noise: blocks, label: "返航导航" },
      { budget: 6, noise: single, label: "两次启动回执" },
      { budget: 61, noise: blocks, label: "编队制动" },
    ],
    packets: [
      packet("return-stop-a", "一号艇停机", { D: 1 }, 1, { priority: "紧急", description: "一条停止指令，单独成包。" }),
      packet("return-stop-b", "二号艇停机", { D: 1 }, 1, { priority: "紧急", description: "另一条停止指令，也要独立保护。" }),
      packet("return-route", "信使号返航路线", normal, 4, { releaseRound: 2, description: "第 2 轮抵达，最迟第 4 轮交付。" }),
      packet("return-go-a", "一号艇启动", { A: 1 }, 3, { releaseRound: 3, description: "第 3 轮抵达，一条前进指令。" }),
      packet("return-go-b", "二号艇启动", { A: 1 }, 3, { releaseRound: 3, description: "第 3 轮抵达，必须与另一艇分别成包。" }),
      packet("return-brake", "返航编队制动", changed, 4, { description: "现在已备好，最迟第 4 轮送达。停止指令占一半。" }),
    ],
    objective: "四轮交付六个必要请求，总成本不超过 134 bit。两个小窗口各只有 6 bit。",
    briefing: "馈线修好了，返航队列却还在增长。第 1、3 轮每包只翻转一位，第 2、4 轮按 7 位块干扰。各包独立保护，接收端会记住本轮码本。先看后面的回执需要哪种码字，再安排长航线。",
    hints: [
      "短回执也要纠错。比较一位数据用重复码和汉明码各要花多少，再看第 3 轮的两条指令。",
      "第 3 轮放不下同步费。第 2 轮留下的码本，必须让两条启动回执都能装进 6 bit。",
      "第 1 轮沿用接收端码本，两条停机用三次重复，共 6 bit。第 2 轮为返航路线生成哈夫曼码，用汉明保护，含同步 61。第 3 轮沿用码本，两条启动用三次重复，共 6。第 4 轮为编队制动生成哈夫曼码，用汉明保护，含同步 61。合计 134 bit。",
    ],
    hint: "短包的保护费用和下一轮的实际码字都需要计算。",
    takeaway: "一位数据用三次重复只需 3 bit，用汉明码却要补齐后发 7 bit。长包通常更适合汉明保护；留下的码本还会影响下一轮短包能否发送。",
    lesson: "lookahead", accent: "blue",
  },
  {
    id: 14, chapter: "两艘船的码本", title: "这一轮最短的码本，撑不到下一艘船", destination: "双子运输船",
    independent: true, difficulty: "高难 · 手工码本",
    kicker: "SHARED CODEBOOK", concept: "跨轮码长分配", budget: 68, rounds: 3, parBits: 145, totalBudget: 145,
    noise: blocks, protections: ["none", "repeat", "hamming"], initialSelected: [],
    initialCoding: "custom", initialCodes: STANDARD_CODES, receiverCodes: STANDARD_CODES, syncCost: 12,
    windows: [
      { budget: 68, noise: blocks, label: "外圈运输船" },
      { budget: 14, noise: blocks, label: "交接回执" },
      { budget: 63, noise: blocks, label: "内圈运输船" },
    ],
    packets: [
      packet("twins-out", "外圈运输船航线", { A: 12, B: 4, C: 1, D: 1 }, 1, { description: "18 条指令，以前进和左转为主。" }),
      packet("twins-handoff", "航道交接回执", { A: 2, D: 2 }, 2, { releaseRound: 2, description: "第 2 轮抵达。只有前进和停止，各两条。" }),
      packet("twins-in", "内圈运输船航线", { A: 6, B: 1, C: 1, D: 12 }, 3, { releaseRound: 3, description: "第 3 轮抵达。停止最多，前进其次。" }),
    ],
    objective: "三轮交付全部航线和交接回执，总成本不超过 145 bit；每次换码本占 12 bit。",
    briefing: "两艘运输船共用接收设备，第二艘的指令频率已经发来。后两轮没有多少余量。你可以直接编辑码字，或自己搭树，试出一套能供两艘船连续使用的码本。",
    hints: [
      "分别计算当前最优、未来最优和定长码的三轮成本。后两轮的容量容得下再次同步吗？",
      "尝试把前进设为 1 位、停止设为 2 位，另外两种设为 3 位。这会增加第一条航线的长度。",
      "第一轮设 A=0、D=10、B=110、C=111，并始终用汉明保护。外圈航线 29 位数据，保护 56，加同步共 68。第二轮 6 位数据，保护 14。第三轮 36 位数据，保护 63。沿用同一码本，共 145 bit。",
    ],
    hint: "自动工具只看当前频率，可以手工给后续常见指令留短码字。",
    takeaway: "当前消息的哈夫曼码未必适合整次任务。本关提前给停止留出 2 位码字，第一轮多花一些，后两轮才能沿用协议完成发送。",
    lesson: "lookahead", accent: "pink",
  },
  {
    id: 15, chapter: "七份小包", title: "码长一样，码字也得对得上", destination: "双子无人站群",
    independent: true, difficulty: "高难 · 分包与同步",
    kicker: "SEVEN ENVELOPES", concept: "补位、码字与切换时机", budget: 21, rounds: 4, parBits: 213, totalBudget: 213,
    noise: blocks, protections: ["none", "repeat", "hamming"], initialSelected: [],
    initialCoding: "custom", initialCodes: { A: "11", B: "10", C: "01", D: "00" },
    receiverCodes: { A: "11", B: "10", C: "01", D: "00" }, syncCost: 12,
    windows: [
      { budget: 21, noise: blocks, label: "确认旧协议" },
      { budget: 110, noise: blocks, label: "长距离巡航" },
      { budget: 49, noise: blocks, label: "两站校准" },
      { budget: 33, noise: blocks, label: "关闭导航台" },
    ],
    packets: [
      packet("seven-stop", "甲站停机回执", { D: 2 }, 1, { description: "两条停止，独立成包。" }),
      packet("seven-check", "乙站四向校验", { A: 1, B: 1, C: 1, D: 1 }, 1, { description: "四种指令各一条，独立成包。" }),
      packet("seven-route", "两站巡航路线", { A: 16, B: 8, C: 4, D: 4 }, 2, { releaseRound: 2, description: "第 2 轮抵达的长包，32 条指令。" }),
      packet("seven-east", "甲站姿态校准", { A: 4, B: 1, C: 1, D: 1 }, 3, { releaseRound: 3, description: "第 3 轮抵达，前进较多。" }),
      packet("seven-west", "乙站姿态校准", { A: 1, B: 4, C: 1, D: 1 }, 3, { releaseRound: 3, description: "第 3 轮抵达，左转较多。不能与甲站合成一包。" }),
      packet("seven-close", "甲站关闭确认", { D: 2 }, 4, { releaseRound: 4, description: "第 4 轮抵达，两条停止。" }),
      packet("seven-park", "乙站泊位指令", { A: 1, B: 1, C: 1, D: 1 }, 4, { releaseRound: 4, description: "第 4 轮抵达，四种指令各一条。" }),
    ],
    objective: "四轮交付七个独立包，总成本不超过 213 bit。检查实际码字和每包补位。",
    briefing: "无人站仍在用它们自己的定长码，四种指令与常用码本的对应顺序相反。七份请求不能合包。各轮频率差别很大，换一次码本都要付同步费，长包和短包也未必适合同一棵树。",
    hints: [
      "先核对接收端的实际码字。相同码长不代表可以免费换成另一套对应关系。",
      "第一轮和第四轮的两个小包用定长码保护只需 21 bit。第二轮的长包需要压缩；第三轮要分别计算两包的补位。",
      "全程用汉明保护。第 1 轮沿用接收端码本，合发两包 21。第 2 轮用长包哈夫曼码，98 加同步 12，共 110。第 3 轮沿用它，合发两包 21+28=49。第 4 轮改用定长编码，21 加同步 12，共 33。总计 213 bit。",
    ],
    hint: "两包的码块要分别向上取整，换码本时还要比较实际码字。",
    takeaway: "两套码长相同的码本仍可能需要同步。第 3 轮重做哈夫曼码无法减少两包合计的保护费，却会多付同步费；最后的小包则值得换回定长码。",
    lesson: "granularity", accent: "gold",
  },
  {
    id: 16, chapter: "安静窗口的队列", title: "本轮能多发一条，后面还够用吗？", destination: "边境维修编队",
    independent: true, difficulty: "高难 · 五轮调度",
    kicker: "RESERVED WINDOWS", concept: "窗口分配与全局余量", budget: 42, rounds: 5, parBits: 220, totalBudget: 220,
    noise: blocks, protections: ["none", "repeat", "hamming"], initialSelected: [],
    initialCoding: "custom", initialCodes: STANDARD_CODES, receiverCodes: STANDARD_CODES, syncCost: 12,
    windows: [
      { budget: 42, noise: blocks, label: "救援艇离站" },
      { budget: 35, noise: quiet, label: "内圈静区" },
      { budget: 61, noise: blocks, label: "维修舰制动" },
      { budget: 68, noise: quiet, label: "外圈静区" },
      { budget: 28, noise: blocks, label: "最后靠港" },
    ],
    packets: [
      packet("queue-urgent", "救援艇离站航线", { A: 4, B: 2, C: 1, D: 1 }, 1, { priority: "紧急", description: "第 1 轮必须交付。" }),
      packet("queue-repair", "维修员接驳航线", { A: 2, B: 1, C: 1 }, 2, { description: "现在可发，最迟第 2 轮交付。" }),
      packet("queue-array", "内圈阵列复位", normal, 4, { releaseRound: 2, description: "第 2 轮抵达，最迟第 4 轮交付。" }),
      packet("queue-brake", "维修舰制动", changed, 3, { releaseRound: 3, priority: "紧急", description: "第 3 轮抵达，并在本轮到期。" }),
      packet("queue-long", "外圈阵列复位", { A: 12, B: 6, C: 3, D: 3 }, 5, { releaseRound: 4, description: "第 4 轮抵达，24 条指令，第 5 轮到期。" }),
      packet("queue-tail", "备用浮标航线", { A: 2, B: 1, C: 1 }, 4, { description: "现在可发，第 4 轮到期。也是必要请求。" }),
      packet("queue-dock", "维修员返回接驳", { A: 2, B: 1, C: 1 }, 4, { releaseRound: 4, description: "第 4 轮抵达，须在本轮交付。" }),
      packet("queue-home", "救援艇靠港", { A: 4, B: 2, C: 1, D: 1 }, 5, { releaseRound: 5, description: "第 5 轮抵达，最后一条靠港航线。" }),
    ],
    objective: "五轮交付八个必要请求，总成本不超过 220 bit。第 2、4 轮没有干扰。",
    briefing: "维修队要把人接回来，两处阵列也在等复位。八份请求有不同的抵达时间，安静窗口只有两次。本轮有空间也不一定该多发；完整计划要把两次换码本的费用算进去。",
    hints: [
      "为两份阵列长包找窗口，再安排短包。提前在干扰中发送短包，会多花多少保护费？",
      "第 2 轮容得下内圈阵列和接驳。第 4 轮要留给外圈长包、备用浮标和返回接驳，还要同步码本。",
      "第 1 轮沿用码本，仅发离站航线，汉明 28。第 2 轮直接发送接驳与内圈阵列，7+28=35。第 3 轮制动哈夫曼加汉明，含同步 61。第 4 轮换回 A=0、B=10、C=110、D=111，直接发外圈阵列、备用浮标、返回接驳，42+7+7+12=68。第 5 轮沿用码本发靠港，汉明 28。共 220 bit。",
    ],
    hint: "先为长包预留安静窗口，再计算提前处理短包是否划算。",
    takeaway: "第 1 轮提前发接驳或备用浮标都是合法方案，但会多耗 7 bit。总预算没有这份余量，短包需要等到合适的安静窗口。",
    lesson: "windows", accent: "blue",
  },
  {
    id: 17, chapter: "先送过去的协议", title: "等短回执抵达，已经来不及换码本", destination: "猎户返航道",
    independent: true, difficulty: "高难 · 提前承诺",
    kicker: "BEFORE THE ACK", concept: "预先同步与混合成本", budget: 41, rounds: 4, parBits: 154, totalBudget: 154,
    noise: quiet, protections: ["none", "repeat", "hamming"], initialSelected: [],
    initialCoding: "custom", initialCodes: STANDARD_CODES, receiverCodes: STANDARD_CODES, syncCost: 12,
    windows: [
      { budget: 41, noise: quiet, label: "导航台尚可通话" },
      { budget: 12, noise: single, label: "两份停机回执" },
      { budget: 63, noise: blocks, label: "穿越猎户航道" },
      { budget: 38, noise: quiet, label: "末段归航" },
    ],
    packets: [
      packet("ahead-out", "导航台切换航线", { A: 12, B: 4, C: 1, D: 1 }, 1, { description: "第 1 轮交付，前进最多。" }),
      packet("ahead-stop-a", "左舷停机回执", { D: 1 }, 2, { releaseRound: 2, description: "第 2 轮抵达，独立的一条停止。" }),
      packet("ahead-stop-b", "右舷停机回执", { D: 1 }, 2, { releaseRound: 2, description: "第 2 轮抵达，必须单独保护。" }),
      packet("ahead-cross", "猎户穿越航线", { A: 6, B: 1, C: 1, D: 12 }, 3, { releaseRound: 3, description: "第 3 轮抵达，停止最多。" }),
      packet("ahead-home", "信使号末段归航", normal, 4, { releaseRound: 4, description: "第 4 轮抵达，前进再次占一半。" }),
      packet("ahead-beacon", "航道浮标定位", { A: 2, B: 1, C: 1 }, 4, { releaseRound: 4, description: "第 4 轮抵达的另一独立包。" }),
    ],
    objective: "四轮交付六个必要请求，总成本不超过 154 bit；后续频率已公开。",
    briefing: "猎户导航台将在第一轮后关闭宽带上行。停机回执和穿越航线随后才到，频率已经预报。每次发送后，接收端会留下本轮协议；你要在仍有余量时决定后面用什么码字。",
    hints: [
      "检查第 2 轮两条停止各用几位，重复和汉明分别要花多少。到那时还有空间同步吗？",
      "第 1 轮可以先使用 A 一位、D 两位、B 和 C 三位的前缀码。把前三轮和最后一轮的成本都算出来。",
      "第 1 轮设 A=0、D=10、B=110、C=111，直接发送 29 位数据，加同步 12，共 41。第 2 轮两包均三次重复，共 12。第 3 轮沿用码本，汉明 63。第 4 轮沿用并直接发两包，30+8=38。共 154 bit；最后一轮重新生成哈夫曼码会多收同步费。",
    ],
    hint: "第 1 轮的方案要能供尚未抵达的短回执使用。",
    takeaway: "未来消息尚未抵达时，也能利用已知频率安排协议。第一次省掉同步费会卡住第二轮；最后一轮看见前进变多，仍要先算更新是否值得。",
    lesson: "lookahead", accent: "pink",
  },
  {
    id: 18, chapter: "等最后一艘船", title: "六个窗口，十份回家的指令", destination: "弥拉返航网络",
    independent: true, difficulty: "终局 · 六轮规划",
    kicker: "UNTIL EVERY SHIP IS HOME", concept: "手工码本与跨窗衔接", budget: 47, rounds: 6, parBits: 195, totalBudget: 195,
    noise: quiet, protections: ["none", "repeat", "hamming"], initialSelected: [],
    initialCoding: "custom", initialCodes: STANDARD_CODES, receiverCodes: STANDARD_CODES, syncCost: 12,
    windows: [
      { budget: 47, noise: quiet, label: "导航台交接" },
      { budget: 12, noise: single, label: "泊位停机确认" },
      { budget: 77, noise: blocks, label: "外圈制动" },
      { budget: 6, noise: single, label: "接驳艇启动" },
      { budget: 59, noise: quiet, label: "末段航线" },
      { budget: 21, noise: blocks, label: "最后靠港" },
    ],
    packets: [
      packet("home-out", "导航台交接航线", { A: 12, B: 4, C: 1, D: 1 }, 1, { description: "18 条指令，前进最多。第 1 轮交付。" }),
      packet("home-stop-a", "左侧泊位停机", { D: 1 }, 2, { releaseRound: 2, priority: "紧急", description: "一条停止指令，独立成包。" }),
      packet("home-stop-b", "右侧泊位停机", { D: 1 }, 2, { releaseRound: 2, priority: "紧急", description: "另一条停止指令，独立成包。" }),
      packet("home-brake", "外圈编队制动", { A: 6, B: 1, C: 1, D: 12 }, 5, { releaseRound: 3, description: "第 3 轮抵达，停止最多，第 5 轮到期。" }),
      packet("home-go-a", "左侧接驳艇启动", { A: 1 }, 4, { releaseRound: 4, description: "第 4 轮抵达，独立的一条前进。" }),
      packet("home-go-b", "右侧接驳艇启动", { A: 1 }, 4, { releaseRound: 4, description: "第 4 轮抵达，不能与另一艇合包。" }),
      packet("home-array", "信使号末段航线", normal, 5, { releaseRound: 5, description: "第 5 轮抵达，16 条指令，本轮到期。" }),
      packet("home-repair", "维修员返回接驳", { A: 2, B: 1, C: 1 }, 5, { releaseRound: 5, description: "第 5 轮抵达，本轮到期。" }),
      packet("home-close", "泊位锁定确认", { D: 2 }, 6, { releaseRound: 6, description: "第 6 轮抵达，两条停止，独立成包。" }),
      packet("home-ella", "信使号最后靠港", { A: 1, B: 1, C: 1, D: 1 }, 6, { releaseRound: 6, description: "第 6 轮抵达。艾拉在等最后四条进站指令。" }),
    ],
    objective: "六轮交付十个必要请求，总成本不超过 195 bit。所有抵达时间、期限和窗口已公开。",
    briefing: "值班表上还有十份请求。停机、接驳和最后的靠港指令都得送到，缺一条就有人留在外面。两个短窗口没有余量更新协议，长窗口还要兼顾后续小包。排完整个队列，算好每次同步，再发第一包。",
    hints: [
      "先检查第 2、4 轮的短回执各需要几位码字，再计算第 6 轮两个独立包的补位。制动航线也不能无限往后推。",
      "前四轮可以共用 A 一位、D 两位、B 和 C 三位的码本。最后两个小包则需要另一种码长分配，要提前留出同步窗口。",
      "第 1 轮设 A=0、D=10、B=110、C=111，直接发交接航线，含同步 41。第 2 轮两条停机用重复码，共 12。第 3 轮沿用码本，制动用汉明 63。第 4 轮两条启动用重复码，共 6。第 5 轮改用定长编码，直接发末段航线和返回接驳，32+8+12=52。第 6 轮沿用定长码，两包汉明共 21。合计 195 bit。",
    ],
    hint: "把码本、保护和同步一起写进六轮计划，检查窄窗口能否沿用前一轮协议。",
    takeaway: "制动航线更新成哈夫曼码虽然能发送，却会卡住下一轮启动回执。末段提前改用定长码会增加当前费用，但最后两个独立小包才能在 21 bit 内交付。",
    lesson: "lookahead", accent: "gold",
  },
];

export const LESSONS: Record<string, Lesson> = {
  bits: {
    title: "消息如何变成比特？",
    intro: "比特是一位 0 或 1。码字把一种指令对应到一串比特；发送方编码，接收方使用同一码本解码。",
    formula: "4 种指令 → 每条 2 bit",
    paragraphs: [
      "定长码的每个码字长度相同，所以边界很容易识别。00 01 10 11 可以分别表示前进、左转、右转、停止。",
      "游戏中的指令含义只影响任务结果。码字的二进制大小没有“更重要”的含义。",
    ],
  },
  prefix: {
    title: "怎样让变长码可以解码？",
    intro: "任何一个码字都不能成为另一个码字的前缀。这让接收端可以沿码树逐位读取，遇到叶子就输出一条消息。",
    formula: "A = 0 · B = 10 · C = 110 · D = 111",
    paragraphs: [
      "上面的码本有效：虽然长度不同，但没有码字是另一个的开头。比特串 010110 可以依次读成 A、B、C。",
      "A = 0、B = 01 存在前缀冲突。读到 0 时，无法立即判断 A 已结束还是 B 尚未结束。本游戏要求使用前缀码。",
      "哈夫曼方法每次合并频率最低的两个节点，将合并后的权重放回，直到只剩一个根。左边记 0，右边记 1。",
    ],
  },
  entropy: {
    title: "频率能告诉我们什么？",
    intro: "信息熵衡量一个消息源的平均不确定性。常见事件携带的自信息较少，罕见事件较多。",
    formula: "H(X) = −Σ p(x) log₂ p(x)",
    paragraphs: [
      "四种指令等概率时，熵是 2 bit/指令。概率为 1/2、1/4、1/8、1/8 时，熵是 1.75 bit/指令。",
      "平均码长 L = Σ p(x) ℓ(x)，其中 ℓ 是该指令的码字长度。对本游戏的逐符号前缀码，平均码长不能低于熵。",
      "哈夫曼码在逐符号二进制前缀码中达到最小平均长度。通常 H ≤ L < H + 1，长度必须是整数，所以 L 不一定恰好等于 H。",
      "这里使用所选消息包的已知频率。真实通信可能要估计频率，还要考虑码本描述、包头、分块等开销。",
    ],
  },
  repeat: {
    title: "重复怎样修复错误？",
    intro: "把一位数据重复三次，再取多数票。000 变成 010 时，接收端仍能恢复 0。",
    formula: "0 → 000 · 1 → 111",
    paragraphs: [
      "保证范围是每个三元组中最多一位出错。若 000 变为 110，多数票反而会恢复成 1。",
      "重复码容易实现，但传输量是原来的三倍。汉明码等纠错方法通过安排校验位，降低保护所需的额外长度。",
    ],
  },
  hamming: {
    title: "让校验结果指向错误",
    intro: "汉明 (7,4) 码在位置 1、2、4 放校验位，在 3、5、6、7 放数据。三个偶校验的结果组成一个位置编号。",
    formula: "[p₁ p₂ d₁ p₄ d₂ d₃ d₄] · 综合值 = s₁ + 2s₂ + 4s₄",
    paragraphs: [
      "校验 1 检查位置 1、3、5、7；校验 2 检查 2、3、6、7；校验 4 检查 4、5、6、7。正常时三个异或结果都为 0。",
      "如果仅位置 5 翻转，综合值是 1 + 0 + 4 = 5。翻转第 5 位即可恢复正确码字。",
      "普通 (7,4) 码保证纠正一个码块中的单比特错误。双错的综合值可能指向另一位，导致误纠正。本游戏使用普通 (7,4) 码，未使用扩展汉明 SECDED 码。",
      "数据长度不是 4 的倍数时，游戏在尾部补 0，再按每 4 位编码成 7 位；解码后根据原始长度移除补位。",
    ],
  },
  joint: {
    title: "先压缩，再加入保护",
    intro: "信源编码利用消息的统计规律缩短表示，信道编码为传输错误增加校验结构。",
    formula: "16 条指令 → 28 bit → 7 × 7 = 49 bit",
    paragraphs: [
      "对 8、4、2、2 的频率，哈夫曼码把原本 32 bit 降为 28 bit。再用汉明 (7,4) 保护，恰好得到 49 bit。",
      "如果给加过校验的数据再做压缩，接收端就无法直接按原来的校验结构纠错。本游戏先做信源编码，再做信道编码；接收时先纠错，再还原指令。",
      "本游戏是有限码块的教学模型。这里的预算不等于香农信道容量，也不演示容量定理的渐近编码过程。",
    ],
  },
  schedule: {
    title: "每条消息都有自己的期限",
    intro: "第 n 轮截止，意味着消息必须在该轮发送结束时正确交付。未交付的必要任务会导致任务失败。",
    formula: "本轮总成本 = Σ 各消息包保护后长度 + 码本同步",
    paragraphs: [
      "每个消息包分别分块和补位，因此两个包的保护成本不能先合并原始长度再计算。预算每轮重置，剩余比特不带入下一轮。",
      "信息熵取决于指令的概率分布，任务优先级和期限取决于救援等实际需求。紧急消息未必有更高的熵。",
      "先保护必须及时交付的消息，再利用余量处理其他任务。直接发送虽然便宜，却可能让指令被噪声改写。",
    ],
  },
  sync: {
    title: "换码本也要占用空间",
    intro: "发送方和接收方必须使用同一码本。带同步成本的任务中，与接收端不同的码本需要 12 bit 的同步控制帧。",
    formula: "更新值得吗？节省的数据成本 > 同步成本",
    paragraphs: [
      "游戏将一次码本同步的费用固定为 12 bit，经可靠控制信道发送。同步帧先于本轮消息发送，之后沿用这套码本就不再收费。",
      "即使两棵树平均长度相同，只要任意指令的码字不同，也需要同步。接收方需要实际对应关系，不能只知道长度。",
      "统计分布变化会影响最合适的码本。更新时要结合待发消息量；短消息里省下的几位，未必足以抵消更新成本。",
    ],
  },
  granularity: {
    title: "哈夫曼最短，为什么总成本未必最少？",
    intro: "哈夫曼码使逐符号二进制前缀码的平均长度最小。实际发送还要按包补齐码块，加入保护和协议开销。",
    formula: "总保护成本 = Σᵢ 7 × ceil(每包信源位数ᵢ / 4)",
    paragraphs: [
      "两个包必须分别补位：一个 2 位包加一个 9 位包需要 1 + 3 个汉明块，共 28 bit。不能先把 11 位合在一起算成 21 bit。",
      "若同一组消息用定长码得到 4 位与 8 位，信源总长度更大，却只需 1 + 2 个汉明块，保护后为 21 bit。",
      "哈夫曼码优化信源平均码长，这里比较的是保护后的总成本。计算实际发送量时，还要计入分包、块长和协议开销。",
    ],
  },
  windows: {
    title: "保护与发送时机一起决定",
    intro: "部分任务提前给出各轮容量和干扰条件。没有干扰的窗口可以省掉保护，大包可能只有在这一轮才装得下。",
    formula: "本轮容量 ≠ 整次值班总预算",
    paragraphs: [
      "清洁信道中直接发送可以省掉保护冗余；有翻转时仍需符合该错误模型的保护。",
      "截止较晚不意味着应该最后发。若以后没有任何窗口容得下它，当前就要为它预留空间。",
      "预报是确定的教学条件，不是对真实宇宙天气的概率预测。进阶关还限制整次值班发送量，所有数据、保护、补位与同步都计入。",
    ],
  },
  lookahead: {
    title: "更新码本前，计算后续成本",
    intro: "码本更新会改变接收端记住的协议。在多轮任务中，要把当前收益、未来数据量和再次同步的费用一起计算。",
    formula: "全局成本 = Σ轮次 (数据保护成本 + 同步成本)",
    paragraphs: [
      "自动工具只根据当前所选消息的频率生成哈夫曼码，不会替你考虑未来窗口、独立补位或码本更新。",
      "相同频率也可能生成不同的码字。交换码树的左右分支，长度不变，但仍需同步新的对应关系。“沿用接收端码本”会恢复对方正在使用的实际码字。",
      "未来消息的抵达轮次、频率与期限都是已公开的计划条件；不能提前发送，但可以提前评估成本。",
    ],
  },
};
